version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    links:
      - bsp

  bsp:
    build:
      context: ./
      dockerfile: bsp.dockerfile
    volumes:
      - ./:/var/www